prefix ptp: <http://example.org/def/production-trace-patterns/>

select distinct
  ?Resource
  ?Event
  (min(?eventTime - ?precedingEventTime) as ?elapsedTime)
where {
  #%VALUES%#

  ?Resource a ptp:Resource .

  ?Event a $EventType ;
    ptp:entity ?Resource ;
    ptp:atTime ?eventTime .

  ?PrecedingEvent a $PrecedingEventType ;
    ptp:entity ?Resource ;
    ptp:atTime ?precedingEventTime .

  filter ( ?eventTime > ?precedingEventTime )
}
group by ?Resource ?Event
order by ?elapsedTime