prefix ptp: <http://example.org/def/production-trace-patterns/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct
  ?Resource
  ?Event
  ?value
  (min(?succeedingEventTime - ?eventTime) as ?elapsedTime)
where {
  #%VALUES%#

  ?Event a $EventType ;
    ptp:entity ?Resource ;
    ptp:atTime ?eventTime ;
    $attribute ?value .

  ?SucceedingEvent a $EventType ;
    ptp:entity ?Resource ;
    ptp:atTime ?succeedingEventTime .

  ?Resource a ptp:Resource , $ResourceType .

  filter ( ?eventTime < ?succeedingEventTime )
}
group by ?Resource ?Event ?value
order by ?elapsedTime