prefix ptp: <http://example.org/def/production-trace-patterns/>

select distinct
  ?Entity
  (max(?intervalEndTime - ?intervalStartTime) as ?elapsedTime)
where {
  #%VALUES%#

  [] a $IntervalStartType ;
    ptp:entity ?Entity ;
    ptp:atTime ?intervalStartTime .

  [] a $IntervalEndType ;
    ptp:entity ?Entity ;
    ptp:atTime ?intervalEndTime .

  ?Entity a $EntityType .

  filter ( ?intervalStartTime < ?intervalEndTime )
}
group by ?Entity
order by ?elapsedTime