prefix ptp: <http://example.org/def/production-trace-patterns/>

construct {
  ?PrecedingEvent ptp:entity ?ProductionEntity .
}
where {
  #%VALUES%#

  ?ProductionEntity a ptp:ProductionEntity .

  ?Event a $EventType ;
    ptp:entity ?ProductionEntity ;
    ptp:entity ?RelatedProductionEntity ;
    ptp:atTime ?eventTime .

  ?RelatedProductionEntity a $RelatedEntityType .

  ?PrecedingEvent ptp:entity ?RelatedProductionEntity ;
    ptp:atTime ?precedingEventTime .

  filter ( ?precedingEventTime < ?eventTime )
  filter ( ?ProductionEntity != ?RelatedProductionEntity )
}