prefix ptp: <http://example.org/def/production-trace-patterns/>

construct {
  ?Event ptp:entity ?PartEntity .
}
where {
  ?Entity a $EntityType .
  ?PartEntity ptp:isPartOf ?Entity .
  {
    ?Event a ptp:Event ;
      ptp:entity ?Entity .
  } union {
    ?Event a ptp:Event ;
      ptp:entity ?PartEntity .
  }
  ?Event a $EventType .
}